name: Codeball
on:
  pull_request:

env:
  GOPROXY: "https://proxy.golang.org"

jobs:
  codeball:
    name: Codeball AI Code Review
    runs-on: ubuntu-latest
    steps:
      - uses: sturdy-dev/codeball-action@v2.6.0
        with:
          approvePullRequests: "true"
          labelPullRequestsWhenApproved: "true"
          labelPullRequestsWhenReviewNeeded: "true"
